app/dash/urls.py
from __future__ import absolute_import
from django.conf.urls import patterns, url

from .views import (Dash, ServerDash, ShopPositionView, ContactAdminView, AdminThankYouView, server_sales_dash,
                    newContactAdminView, message_thread)

urlpatterns = patterns('',
                       url(r'^shop-dashboard$', Dash.as_view(), name='dash'),
                       url(r'^server-dashboard$', ServerDash.as_view(), name='server-dash'),
                       url(r'^server-sales-dashbaord',server_sales_dash,name='sales-dashboard'),
                       url(r'^shop/postion/$', ShopPositionView.as_view(), name='shop-position'),
                       url(r'^contact/admin/$', newContactAdminView, name='contact-admin'),
                       url(r'^messages/(?P<id>\d+)/$',message_thread,name='message-thread'),
                       url(r'^contact/admin/thankyou$', AdminThankYouView.as_view(template_name="urpsm/v2/dash/admin_thankyou_v2.html"), name='adminthankyou'),
                       url(r'^send-feedback$', 'app.dash.views.send_feedback', name='manager-send-feedback'),
                       )

mobilify/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.http import HttpResponse

from app.dash.sites import SitePlus
from django.conf.urls.i18n import i18n_patterns
from app.account.views import Error404View

admin.site = SitePlus()
admin.autodiscover()

urlpatterns = i18n_patterns('',
                       # Examples:
                       # url(r'^$', 'mobilify.views.home', name='home'),
                       url(r'', include('app.public.urls')),
                       url(r'^orders/', include('app.order.urls')),
                       url(r'^accounts/', include('app.account.urls')),
                       url(r'^shop/', include('app.shop.urls')),
                       url(r'^clients/', include('app.client.urls')),
                       url(r'^components/', include('app.component.urls')),
                       url(r'^server/', include('app.server.urls')),
                       url(r'^select2/', include('django_select2.urls')),
                       url(r'^chaining/', include('smart_selects.urls')),
                       url(r'^notifications/', include('app.notifications.urls')),
                       url(r'^payments/', include('app.payment.urls')),
                       url(r'^tickets/', include('app.ticket.urls')),
                       url(r'^reviews/', include('app.ureview.urls')),
                       url(r'^manager/', include('app.dash.urls')),
                       url(r'^endpoint/', include('app.endpoint.dash_urls')),
                       url(r'^location_field/',
                           include('location_field.urls')),
                       url(r'^payment/',
                           include('paypal.standard.ipn.urls')),
                       url(r'^error', Error404View.as_view(), name='error-404'),
                       url(r'secure/', include('two_factor.urls', 'two_factor')),
                       url(r'sitemap.xml',lambda r: HttpResponse(open('sitemap.xml','r').read(),status=200)))

urlpatterns +=    patterns('',url(r'^urpsmadminp/', include(admin.site.urls)),
                       url(r'^', include('app.endpoint.urls')),
                       url(r'^', include('app.launch.urls')),
                       url(r'', include('social.apps.django_app.urls', namespace='social')),
                       url(r'^search/', include('app.search.urls')),
                       url(r'session_security/', include('session_security.urls')),
                    )

if settings.DEBUG:
    urlpatterns +=patterns('',
                            (r'^static/(?P<path>.*)$', 'django.views.static.serve',
                             {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
                            )

    urlpatterns += patterns('',
                            (r'^media/(?P<path>.*)$', 'django.views.static.serve',
                             {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
                            )

app/dash/models.py
from django.db.models import ForeignKey, CharField, EmailField, TextField, URLField, DateTimeField, Model, BooleanField
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.conf import settings

from app.server.models import Server
from app.shop.models import Shop

CHOICES = (('','--'),('admin', _('administrative')), ('tech',_('technical')), ('money',_('financial')))

class ContactAdmin(Model):
    user        = ForeignKey(User, related_name="sender" )
    subject     = CharField(max_length=255, default="Hello", blank=False, null=False )
    type        = CharField(max_length=5, blank=True, null=True, choices=CHOICES, default='')
    created_at  = DateTimeField(auto_now=True)
    message     = TextField(max_length=2048, blank=False, null=False)
    feedback    = TextField(max_length=2048, blank=True, null=True, default='')
    processed   = BooleanField(default=False)

    class Meta:
        verbose_name        = "Admin Contact"
        verbose_name_plural = "Admin Contacts"

    def __str__(self):
        return "{0}:{1}-{2}".format(self.user, self.type ,self.subject)

class KeyValueStore(Model):
    key  = TextField(null=False)
    title = CharField(max_length=60,null=False)
    category = CharField(max_length=30,blank=True,null=True)
    value =TextField(blank=True)
    active = BooleanField(default=True)

cat_choice = (('ADMINISTRATIVE','ADMINISTRATIVE'),('TECHNICAL','TECHNICAL'),('FINANCIAL','FINANCIAL'))
status_choice = (('OPEN','OPEN'),('SOLVED','SOLVED'))

class MessageThread(Model):
    subject = CharField(max_length=60)
    type = CharField(max_length=30,choices=cat_choice)
    active = BooleanField(default=True)
    status = CharField(max_length=30,choices=status_choice,default='OPEN')
    shop = ForeignKey(Shop,null=True,default=None)
    server = ForeignKey(Server,null=True,default=None)
    created_at = DateTimeField(auto_now_add=True)

    @property
    def first_message(self):
        return Message.objects.filter(thread=self).order_by('datetime').first()

class Message(Model):
    thread = ForeignKey(MessageThread)
    from_user = ForeignKey(User)
    message = TextField()
    datetime = DateTimeField(auto_now_add=True)

class AdminActionHistory(Model):
    action = CharField(max_length=100)
    created = DateTimeField(auto_now_add=True)
    user = ForeignKey(settings.AUTH_USER_MODEL)
    affected = TextField(blank=True,null=True)

app/dash/forms.py
from django import forms
from django.utils.translation import activate,ungettext_lazy, ugettext as _
from .models import ContactAdmin, CHOICES
from django.utils.translation import ugettext_lazy as _


class ContactAdminForm(forms.ModelForm):
    subject = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': _('subject')}))
    type = forms.CharField(required=True, widget=forms.Select(
        attrs={'class': 'form-control', 'placeholder': _('type')}, choices=CHOICES))

    message = forms.CharField(required=True, widget=forms.Textarea(
        attrs={'class': 'form-control', 'rows':6 , 'placeholder': _('Write message here')}))

    class Meta:
        model = ContactAdmin
        exclude = ('created_at', )

app/dash/views.py
import arrow
from decimal import Decimal
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, DetailView, FormView, ListView
from django.contrib.auth.models import User
from django.http import Http404
from django.http.response import JsonResponse, HttpResponse
from django.contrib.admin.views.decorators import staff_member_required
from django.core.urlresolvers import  reverse, reverse_lazy
from django.core.mail import send_mail
from django.shortcuts import redirect, get_object_or_404, render
from django.utils.safestring import mark_safe
from django.db.models import Count, Max
from django.utils.translation import ugettext_lazy as _
from django.db.models.aggregates import Sum

from app.account.utils import mailer
from app.payment.models import DEBIT
from app.shop.models import Shop, Invoices, InvoiceCharges
from app.component.models import Component
from braces.views import LoginRequiredMixin
from app.client.models import Client
from datetime import datetime
from django.utils import timezone
import random
import arrow
from mobilify.settings import DEFAULT_FROM_EMAIL
from app.phone.models import Brand
from app.notifications.models import Notification
from app.shop.models import Shop
from app.server.models import Server, ServerSales
from app.ticket.models import OrderTicket, TicketMessage
from app.order.models import ServerOrder, COMPLETED, CANCELLED, REJECTED, Charges
from app.ureview.models import ShopReview, ServerReview
from app.order.models import ShopOrder
from el_pagination.views import AjaxListView
from simplecities.models import City, Country
from app.account.views import HasBusinessMixin
from .forms import ContactAdminForm
from .models import ContactAdmin, KeyValueStore, AdminActionHistory, MessageThread, Message
from app.payment import utils as payment_utils


@login_required
def AdminSupportTicket(request,pk):
    if not request.user.is_superuser:
        redirect(reverse_lazy('login'))
    ticket = get_object_or_404(OrderTicket, pk=pk)
    ticket_messages = TicketMessage.objects.filter(order_ticket=ticket)
    order = ticket.server_order
    return render(request,"urpsm/v2/dash/customOrderReply.html",{'ticket':ticket,'ticket_messages':ticket_messages,'order':order},status=200)

@login_required
def AdminViewActionHistory(request):
    if not request.user.is_superuser:
        redirect(reverse_lazy('login'))
    history = AdminActionHistory.objects.all().order_by('-created')
    return render(request,"urpsm/v2/dash/adminhistory.html",{"actions":history})

@login_required
def edit_meta(request):
    if not request.user.is_superuser:
        redirect(reverse_lazy('login'))
    if request.method == 'POST':
        url = request.POST['url']
        value = request.POST[url]
        kv = KeyValueStore.objects.get(pk=int(url))
        kv.value = value
        kv.save()
    urls = KeyValueStore.objects.filter(category='MetaTags')
    return render(request,'urpsm/v2/dash/metaedit.html',{"urls":urls})

@login_required
@csrf_exempt
def edit_site_texts(request):
    if not request.user.is_superuser:
        redirect(reverse_lazy('login'))

    if request.method == 'POST':
        for id in request.POST.keys():
            AdminActionHistory.objects.create(action="Deposit Text edited", user=request.user, affected="")

            t = KeyValueStore.objects.get(pk=id)
            t.value = request.POST[id]
            t.save()
    texts = KeyValueStore.objects.filter(category="Deposit Texts")
    ret_texts = []
    for text in texts:
        ret_texts.append({'id': text.id, 'title': text.title, 'value': mark_safe(text.value)})
    return render(request,"urpsm/v2/dash/urpsm_texts.html",{"texts":ret_texts})

@login_required
@csrf_exempt
def edit_deposit_info(request):
    if not request.user.is_superuser:
        redirect(reverse_lazy('login'))

    if request.method == 'POST':
        for id in request.POST.keys():
            AdminActionHistory.objects.create(action="Deposit Info edited", user=request.user, affected="")

            t = KeyValueStore.objects.get(pk=id)
            t.value = request.POST[id]
            t.save()
    texts = KeyValueStore.objects.filter(category="Deposit Infos")
    ret_texts = []
    for text in texts:
        ret_texts.append({'id': text.id, 'title': text.title, 'value': mark_safe(text.value)})
    return render(request, "urpsm/v2/dash/deposit_info_text.html", {"texts": ret_texts})


@csrf_exempt
@login_required
@transaction.atomic
def view_clearance_requests(request):
    if not request.user.is_superuser:
        redirect(reverse_lazy('login'))

    if request.method == 'POST':
        clearance_id = request.POST['clear']
        obj = ServerSales.objects.get(id=clearance_id,active=True)
        s_obj = ServerSales.objects.get(server=obj.server,type="available_withdraw",active=True)
        t_obj = ServerSales.objects.get(server=obj.server,type="amount_completed",active=True   )
        if t_obj.value < obj.value:
            return HttpResponse('Not enough available order balance available')
        t_obj.value -= obj.value
        s_obj.value = obj.value
        obj.active = False
        ServerSales.objects.create(server=obj.server,type="askedfor_clearance",active=True,value=Decimal(0.0))
        obj.save()
        s_obj.save()
        t_obj.save()
        AdminActionHistory.objects.create(action="Clearance request for "+str(obj.value)+" cleared #"+str(obj.id), user=request.user, affected="")
        '''
        notification = 'URPSM # has cleared amount  $' + str(obj.value) + ' for withdrawl.'
        mailer("urpsm/notifications/email_notifications.html", "URPSM: Notification",
               ctx={
                   'notification': notification},
               recipient=obj.server.server_email,
               fromemail="notifications@urpsm.com")
        '''
        return HttpResponse("Cleared",status=200)

    charges = ServerSales.objects.filter(type="askedfor_clearance").exclude(value=Decimal(0.0))
    return render(request,"admin/dash/clearforwithdrawl.html",{'charges':charges})


@csrf_exempt
@login_required
@transaction.atomic()
def view_shop_invoices(request):
    if not request.user.is_superuser:
        redirect(reverse_lazy('login'))
    if request.method == 'POST':
        chargetext = request.POST['chargetext']
        chargevalue = request.POST['chargevalue']
        invoiceid = request.POST['invoice']
        invoice = Invoices.objects.get(id=invoiceid)
        if '%' in chargevalue:
            charge_amount = invoice.amount * Decimal(chargevalue[:-1])/100
        else:
            charge_amount = Decimal(chargevalue)
        if invoice.shop.balance < charge_amount:
            return HttpResponse("Shop balance is less than the charge amount. Transcation rejected. Please try again")
        AdminActionHistory.objects.create(action="Charge added to invoice, amount:"+str(chargevalue)+ ", id:"+str(invoice.id), user=request.user, affected="Invoice")
        invoice.shop.balance -= charge_amount
        invoice.shop.save()
        InvoiceCharges.objects.create(invoice=invoice,charge_text=chargetext,charge_amount=charge_amount)
        payment_utils.create_shop_payment_transaction(invoice.shop,charge_amount,invoice.shop.balance,DEBIT,chargetext + " against invoice #"+str(invoice.id))
        extra_charges = InvoiceCharges.objects.filter(invoice=invoice)
        amount = invoice.amount
        for i in extra_charges:
            amount += i.charge_amount

        return render(request, 'urpsm/shop/pdfinvoice.html', {"invoice": invoice,"extra_charges":extra_charges,"amount":amount})
    invoices = Invoices.objects.all().order_by('-created')
    return render(request, "admin/shop/shop_view_invoice.html", {'invoices': invoices})

@login_required
def urpsm_charges(request):
    if not request.user.is_superuser:
        redirect(reverse_lazy('login'))
    if request.method == 'POST':
        forall_cancel = request.POST['order_cancellation_charges_forall']
        order_cancellation_charge = request.POST['order_cancellation_charges']
        charge = Charges.objects.get(charge='order_cancellation_charges')
        charge.value = order_cancellation_charge
        charge.save()
        if forall_cancel == 'true':
            shops = Shop.objects.all()
            for shop in shops:
                if shop.cancellation_charges is not None:
                    shop.cancellation_charges = None
                    shop.save()
        AdminActionHistory.objects.create(action="URPSM Charges altered", user=request.user, affected="Charges")
        forall_complete = request.POST['order_shop_completion_charges_forall']
        order_completion_charge = request.POST['order_shop_completion_charges']
        charge = Charges.objects.get(charge='order_shop_completion_charges')
        charge.value = order_completion_charge
        charge.save()
        if forall_complete == 'true':
            shops = Shop.objects.all()
            for shop in shops:
                if shop.completion_charges is not None:
                    shop.completion_charges = None
                    shop.save()

        forall_complete = request.POST['order_completion_charges_forall']
        order_completion_charge = request.POST['order_completion_charges']
        charge = Charges.objects.get(charge='order_completion_charges')
        charge.value = order_completion_charge
        charge.save()
        if forall_complete == 'true':
            servers = Server.objects.all()
            for server in servers:
                if server.completion_charges is not None:
                    server.completion_charges = None
                    server.save()
        return render(request, 'admin/dash/charges.html')
    else:
        c_complete_charge= Charges.objects.get(charge='order_completion_charges').value

templates/urpsm/v2/dash/admin_thankyou_v2.html
{% extends "urpsm/v2/base_manager_v2.html" %}
{% load static from staticfiles %}{% load i18n%}
{% block title %} {% trans 'contact admin'|capfirst %} {% endblock %}
{% block heading %} {% trans 'contact admin'|capfirst %} {% endblock %}
{% block content %}
<div class="row" style="margin:10px 0;">
  <h1 class="onwan" style="text-align: left;margin-left: 15px;">{% trans 'thank you'|capfirst %}</h1>
</div>
<script type="text/javascript">setTimeout(function(){ window.location.href ="{% url 'contact-admin' %}" }, 3000);</script>
{% endblock content %}

templates/urpsm/v2/dash/base_dashboard_v2.html
{% extends "urpsm/v2/base_manager_v2.html" %}
{% load static from staticfiles %}{% load i18n%}
{% block title %} {% trans 'Dashboard'|capfirst %} {% endblock %}
{% block heading %} {% trans 'Dashboard'|capfirst %} {% endblock %}

{% block content %}
{% endblock %}

{% block extrastyle %}
{% endblock %}
{% block extrajs %}
   
</script>
{% endblock %}

templates/urpsm/v2/dash/contact_admin_v2.html
{% extends "urpsm/v2/base_manager_v2.html" %}
{% load static from staticfiles %}{% load i18n%}
{% block title %} {% trans 'contact admin'|capfirst %} {% endblock %}
{% block heading %} {% trans 'contact admin'|capfirst %} {% endblock %}
{% block content %}
<div class="row" style="margin:10px 0;">
    <div slass="col-xs-12" style="margin-left:10px;margin-right:10px">
      <div class="box">
          <div class="box-header with-border">
            <h3 class="box-title">{% trans 'contact admin'|capfirst %} </h3>
          </div>

          <div class="box-body">
            <form role="form" method="post" action="{% url 'contact-admin' %}">
                {% csrf_token %}
            <div class="col-md-12">
            	<div class="col-md-4">
	                <div class="form-group">
	                    <label>Subject</label>
		                <input class="form-control" id="id_subject" name="subject" placeholder="subject" type="text">

	                </div>

	                <div class="form-group">
	                   <label>Type</label>
		                <select class="form-control" id="id_type" name="type" placeholder="type">
<option value="" selected="selected">--</option>
<option value="ADMINISTRATIVE">ADMINISTRATIVE</option>
<option value="TECHNICAL">TECHNICAL</option>
<option value="FINANCIAL">FINANCIAL</option>
</select>

	                </div>
	            </div>

            	<div class="col-md-8">
		             <div class="form-group">
		                <label>Message</label>
                            <textarea class="form-control" cols="40" id="id_message" name="message" placeholder="Write message here" rows="6"></textarea>

		              </div>
		        </div>
            </div>
          </div>
          <div class="box-footer">
            <input  type="submit" class="btn btn-primary pull-right" value="{% trans 'send'|capfirst %}"/>
          </div>
         </form>
      </div>
    </div>

    <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">{% trans 'previous admin messages'|capfirst %}</h3>
            </div>
            <div class="box-body table-responsive">
              <table class="table table-hover table-bordered">
                <tbody><tr>
                  <th>{% trans 'subject'|capfirst %}</th>
                  <th>{% trans 'type'|capfirst %}</th>
                  <th>{% trans 'message'|capfirst %}</th>
                  <th>{% trans 'status'|capfirst %}</th>
                  <th>{% trans 'date'|capfirst %}</th>
                </tr>
                {% for message in messages%}
                <tr>

                    <td><a href="{% url 'message-thread' message.id %}">{{message.subject}}</a></td>
                  <td><span class="label" style="background: #fc8675;">{{message.type}}</span></td>
                  <td>{{message.first_message.message}}</td>
                    <td><span class="label" style="background: #fc8675;">{{message.status}}</span></td>
                  <td>{{message.created_at}}</td>
                </tr>
                <!-- ****************** modal ********************-->
				<!-- ****************** end modal ********************-->
                {%endfor%}
           

              </tbody></table>
            </div>
            <div class="box-footer clearfix">
              {% if is_paginated %}
              <ul class="pagination pagination-sm no-margin pull-right">
                {% if page_obj.has_previous %}
              <li>
                <a href="?{% if query %}q={{ query }}&{% endif %}page={{ page_obj.previous_page_number }}" title="{% trans 'Previous' %}">{% trans 'previous'|capfirst %}</a>
                  </li>
                  {% endif %}
                  <li>
                      <span class="current">{% trans 'Page' %} {{ page_obj.number }} {% trans 'of' %} {{ page_obj.paginator.num_pages }}</span>
                  </li>
                  {% if page_obj.has_next %}
                  <li>
                      <a href="?{% if query %}q={{ query }}&{% endif %}page={{ page_obj.next_page_number }}" title="{% trans 'Next' %}">{% trans 'next'|capfirst %}</a>
                  </li>
                  {% endif %}
              </ul>
              {% endif %}
            </div>
          </div>
          <!-- /.box -->
    </div>
</div>



<!-- ****************** end model ********************-->
{% endblock content %}

templates/urpsm/v2/dash/contact_shop_server.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static admin_list admin_urls suit_list suit_tags %}
{% load url from suit_compat %}
 {% load i18n thumbnail staticfiles account_tags %} {% block title %} {% trans 'Messages'|capfirst %} {% endblock %} {% block heading %} {% trans 'orders'|capfirst %} {% endblock %} {% block breadcrumb %}
<li class="active">{% trans 'Messages'|capfirst %}</li>
{% endblock %}

{% block extrahead %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
  $(".searchselect").select2();
});

</script>

{% endblock %}
{% block content %}
<div class="row" style="margin:10px 0;">
    <div slass="col-xs-12" style="margin-left:10px;margin-right:10px">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">{% trans 'New Message'|capfirst %} </h3>
            </div>

            <div class="box-body">
                <form role="form" method="post">
                    {% csrf_token %}
                    <div class="col-md-12">
                        <div class="span4">

                            <div class="btn-group" data-toggle="buttons-radio">
    <label for="leftradio" class="btn btn-primary" onclick="$('#shopselectform').show();$('#serverselectform').hide();">Shop</label>
    <input type="radio" name="to" value="shop" id="leftradio" style="display:none;" checked />
    <label for="rightradio" style="border-radius:0px 4px 4px 0px;" class="btn btn-primary" onclick="$('#shopselectform').hide();$('#serverselectform').show();">Server</label>
    <input type="radio" name="to" value="server" id="rightradio" style="display:none;" />
</div><br>


                            <div class="form-group" id="shopselectform">
                                <label for="id_shopselect">Shop:</label>

                                <select class="form-control searchselect" id="id_shopselect" name="shop">
                                    <option value="" selected="selected">SELECT A SHOP</option>
                                        {% for shop in allshops %}
                                        <option value="{{ shop.id }}">{{ shop.name }}</option>
                                        {% endfor %}
                                </select>

                            </div>
                            <div class="form-group" id="serverselectform" style="display:none;">
                                <label for="id_serverselect">Server:</label>

                                <select class="form-control searchselect" id="id_serverselect" name="server">
                                    <option value="" selected="selected">SELECT A SERVER</option>
                                        {% for server in allservers %}
                                        <option value="{{ server.id }}">{{ server.name }}</option>
                                        {% endfor %}
                                </select>

                            </div>
                            <div class="form-group">

                                <label>Subject</label>
                                <input class="form-control" id="id_subject" name="subject" placeholder="subject"
                                       type="text">

                            </div>

                            <div class="form-group">
                                <label>Type</label>
                                <select class="form-control" id="id_type" name="type" placeholder="type">
                                    <option value="" selected="selected">--</option>
                                    <option value="ADMINISTRATIVE">ADMINISTRATIVE</option>
                                    <option value="TECHNICAL">TECHNICAL</option>
                                    <option value="FINANCIAL">FINANCIAL</option>
                                </select>

                            </div>
                        </div>

                        <div class="col-md-8">
                            <div class="form-group">
                                <label>Message</label>
                                <textarea class="form-control" cols="40" id="id_message" name="message"
                                          placeholder="Write message here" rows="9"></textarea>

                            </div>
                        </div>
                    </div>
            </div>
            <div class="box-footer">
                <input type="submit" class="btn btn-primary pull-right" value="{% trans 'send'|capfirst %}"/>
            </div>
            </form>
        </div>
    </div>

    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">{% trans 'messages'|capfirst %}</h3>
            </div>
            <div class="box-body table-responsive">
                <table class="table table-hover table-bordered">
                    <tbody>
                    <tr>
                        <th>{% trans 'subject'|capfirst %}</th>
                        <th>{% trans 'type'|capfirst %}</th>
                        <th>{% trans 'Shop/Server'|capfirst %}</th>

                        <th>{% trans 'name'|capfirst %}</th>
                        <th>{% trans 'message'|capfirst %}</th>
                        <th>{% trans 'status'|capfirst %}</th>
                        <th>{% trans 'date'|capfirst %}</th>
                    </tr>
                    {% for message in cmessages %}
                    <tr>
                        <td><a href="{% url 'message-thread' message.id %}">{{message.subject}}</a></td>
                        <td><span class="label" style="background: #fc8675;">{{message.type}}</span></td>
                        <td>{% if message.shop %}<span class="label" style="background: #98f442;">Shop</span>{% endif %}
                            {% if message.server %}<span class="label" style="background: #4dbde2;">Server</span>{% endif %}</td>
                        <td>{% if message.shop %}{{ message.shop.name }}{% endif %}{% if message.server %}{{ message.server.name }}{% endif %}</td>
                        <td>{{message.first_message.message}}</td>
                        <td><span class="label" style="background: #fc8675;">{{message.status}}</span></td>
                        <td>{{message.created_at}}</td>
                    </tr>
                    <!-- ****************** modal ********************-->
                    <!-- ****************** end modal ********************-->
                    {%endfor%}


                    </tbody>
                </table>
            </div>
            <div class="box-footer clearfix">
                {% if is_paginated %}
                <ul class="pagination pagination-sm no-margin pull-right">
                    {% if page_obj.has_previous %}
                    <li>
                        <a href="?{% if query %}q={{ query }}&{% endif %}page={{ page_obj.previous_page_number }}"
                           title="{% trans 'Previous' %}">{% trans 'previous'|capfirst %}</a>
                    </li>
                    {% endif %}
                    <li>
                        <span class="current">{% trans 'Page' %} {{ page_obj.number }} {% trans 'of' %} {{ page_obj.paginator.num_pages }}</span>
                    </li>
                    {% if page_obj.has_next %}
                    <li>
                        <a href="?{% if query %}q={{ query }}&{% endif %}page={{ page_obj.next_page_number }}"
                           title="{% trans 'Next' %}">{% trans 'next'|capfirst %}</a>
                    </li>
                    {% endif %}
                </ul>
                {% endif %}
            </div>
        </div>
        <!-- /.box -->
    </div>
</div>


<!-- ****************** end model ********************-->
{% endblock content %}