app/endpoint/urls.py
from __future__ import absolute_import
from django.conf.urls import patterns, url
from django.http import HttpResponse

urlpatterns = patterns('',
                       url(r'^get_services/$',
                           'app.endpoint.views.get_services',
                           name="get_services"),
                      
                       url(r'^get_service_detail/$',
                           'app.endpoint.views.get_service_detail',
                           name="get_service_detail"),

                       url(r'^save-selected-services/$',
                           'app.endpoint.views.save_selected_services',
                           name="endpoint-services"),

                       url(r'^set-credit$',
                           'app.endpoint.views.set_credit',
                           name="endpoint-server-credit"),
                       url(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\n\nAllow: /",status=200)),

                       )

app/order/urls.py
from __future__ import absolute_import
from django.conf.urls import patterns, url

from app.ureview.views import create_server_order_review
from .views import UnlockingView, ServerOrdersView, ServiceDown, ServerOrderDetailView, CancelServerOrderView, ServerOrderTicketsListView, \
    UnlockingViewF

urlpatterns = patterns('',
                       url(r'^$', ServerOrdersView.as_view(),
                           name='orders'),
                       url(r'^servicebusy/$', ServiceDown.as_view(),
                           name='servicebusy'),
                       url(r'^create/$', UnlockingViewF,
                           name='unlocking'),
                       url(r'^(?P<pk>\d+)/detail/$',
                           ServerOrderDetailView.as_view(), name='order-detail'),
                       url(r'^(?P<pk>\d+)/cancel/$',
                           CancelServerOrderView.as_view(), name='cancel-order'),
                       url(r'^tickets/', ServerOrderTicketsListView.as_view(), name="order-tickets"),
                       url(r'^review', create_server_order_review, name='server-order-review'),
                       # url(r'^(?P<order_id>\d+)/cancel-order/$',
                       #     cancel_server_order,
                       #     name="cancel_server_order"),
                       )

mobilify/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.http import HttpResponse

from app.dash.sites import SitePlus
from django.conf.urls.i18n import i18n_patterns
from app.account.views import Error404View

admin.site = SitePlus()
admin.autodiscover()

urlpatterns = i18n_patterns('',
                       # Examples:
                       # url(r'^$', 'mobilify.views.home', name='home'),
                       url(r'', include('app.public.urls')),
                       url(r'^orders/', include('app.order.urls')),
                       url(r'^accounts/', include('app.account.urls')),
                       url(r'^shop/', include('app.shop.urls')),
                       url(r'^clients/', include('app.client.urls')),
                       url(r'^components/', include('app.component.urls')),
                       url(r'^server/', include('app.server.urls')),
                       url(r'^select2/', include('django_select2.urls')),
                       url(r'^chaining/', include('smart_selects.urls')),
                       url(r'^notifications/', include('app.notifications.urls')),
                       url(r'^payments/', include('app.payment.urls')),
                       url(r'^tickets/', include('app.ticket.urls')),
                       url(r'^reviews/', include('app.ureview.urls')),
                       url(r'^manager/', include('app.dash.urls')),
                       url(r'^endpoint/', include('app.endpoint.dash_urls')),
                       url(r'^location_field/',
                           include('location_field.urls')),
                       url(r'^payment/',
                           include('paypal.standard.ipn.urls')),
                       url(r'^error', Error404View.as_view(), name='error-404'),
                       url(r'secure/', include('two_factor.urls', 'two_factor')),
                       url(r'sitemap.xml',lambda r: HttpResponse(open('sitemap.xml','r').read(),status=200)))

urlpatterns +=    patterns('',url(r'^urpsmadminp/', include(admin.site.urls)),
                       url(r'^', include('app.endpoint.urls')),
                       url(r'^', include('app.launch.urls')),
                       url(r'', include('social.apps.django_app.urls', namespace='social')),
                       url(r'^search/', include('app.search.urls')),
                       url(r'session_security/', include('session_security.urls')),
                    )

if settings.DEBUG:
    urlpatterns +=patterns('',
                            (r'^static/(?P<path>.*)$', 'django.views.static.serve',
                             {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
                            )

    urlpatterns += patterns('',
                            (r'^media/(?P<path>.*)$', 'django.views.static.serve',
                             {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
                            )

app/endpoint/models.py
from __future__ import absolute_import
from django.db import models
from app.dhrufusion.client import Client as DhruClient
from app.nakshfusion.client import Client as NakshClient
from app.nakshfusion.gsm_client import Client as GsmClient
from app.shop.models import Shop
from app.server.models import Server
from app.search.index import Indexed, SearchField, FilterField, RelatedFields
from django.utils.translation import ugettext_lazy as _

def get_providers():
    return ( ('',''), ('dhru', 'DHRU'), ('naksh', 'Naksh Soft'),('gsm','Gsm Genie') )



class Network(models.Model):
    name = models.CharField(max_length=255)
    services = models.TextField()  # can pass attributes like null, blank, etc.
    
    def __str__(self):
        return unicode(self.name)

class Endpoint(models.Model, Indexed):
    server   = models.ForeignKey(Server, null=True, related_name="server_endpoint")
    url      = models.URLField(unique=True)
    username = models.CharField(max_length=255)
    key      = models.CharField(max_length=255)
    networks = models.ManyToManyField(Network, blank=True, default=None)
    provider = models.CharField(max_length=16, choices=get_providers(), blank=False, null=False, default='dhru')
    active   = models.BooleanField(default=False)

    def __str__(self):
        return "%s endpoint" % unicode(self.server.name)

    def delete(self, using=None, keep_parents=False):
        self.active = False
        self.save()
    
    # @property 
    def get_client(self):
        client = 'None'
        if self.provider == 'dhru':
            client = DhruClient(username=self.username, apiaccesskey=self.key,
                   dhrufusion_url=self.url)
        elif self.provider == 'naksh':
            client = NakshClient(userId=self.username, apiKey=self.key,
                    nakshfusion_url=self.url)
        elif self.provider == 'gsm':
            client = GsmClient(userId=self.username, apiKey=self.key,
                                 gsm_url=self.url,server=self.server)
        return client

    def get_credit(self):
        client = 'None'
        if self.provider == 'dhru':
            credit = self.client.get_credit()
        elif self.provider == 'naksh' or self.provider == 'gsm':
            credit = self.server.credit
        return credit
    
    client = property(get_client)
    credit = property(get_credit)

    @property
    def status(self):
        try:
            c = self.client.status()
            return c
        except: return False

    def account_info(self):
        if self.status:
            c = self.client
            if c:
                return c.get_credit()
        return False

    def service_info(self, id=None):
        if self.status:
            c = self.client
            if c:   
                return c.get_imei_service_details(id=id)
        return False

    def service_info_new(self,id):
        if self.status:
            c = self.client
            if c:
                return c.get_imei_service_detail_new(id=id)
        return None

    def place_order(self, service_id, imei):
        if self.status:
            c = self.client
            if c:
                return c.place_imei_order(service_id, imei)
        return False

    def order_info(self, id):
        if self.status:
            c = self.client
            if c:
                return c.get_imei_order(id)
        return False

    def get_networks_count(self):
        return self.networks.count()

    search_fields = [
        FilterField('active'),
        SearchField('url'),
        SearchField('provider'),
        RelatedFields('networks', [
            SearchField('name', partial_match=True, boost=10),
            SearchField('services', partial_match=True, boost=10),
        ]),
        RelatedFields('server', [
            SearchField('name', partial_match=True, boost=10),
            SearchField('slug', partial_match=True, boost=10),
            SearchField('description', partial_match=True, boost=10),
            SearchField('address'),
            SearchField('website'),
            SearchField('twitter'),
            SearchField('facebook'),
            SearchField('google_plus'),
            FilterField('blocked'),
            FilterField('created'),
            FilterField('level'),
            FilterField('rank'),
            FilterField('performance'),
            FilterField('average_rating'),
        ]),
        ]

    class Meta:
        unique_together = (('url',),)

app/order/models.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import
import json
from django.db import models
# from uuidfield import UUIDField
from app.shop.models import Shop
from app.server.models import Server
from app.client.models import Client
from app.endpoint.models import Endpoint
from app.phone.models import Brand, Model
from django.conf import settings
from django.contrib.auth.models import User
from decimal import Decimal
from django.core.validators import MinValueValidator
from app.antifraud.validators import validate_imei

PENDING     = 'PENDING'
DELIVERED   = 'DELIVERED'
REJECTED    = 'REJECTED'
CANCELLED   = 'CANCELLED'
COMPLETED   = 'COMPLETED'
HOLD        = 'HOLD'
CANT_REPAIR = 'CANT_REPAIR'
NEED_YOUR_CALL = 'NEED_YOUR_CALL'
READY          = 'READY'

ORDER_STATUSES = (
    (PENDING, 'PENDING'),
    (DELIVERED, 'DELIVERED'),
    (REJECTED, 'REJECTED'),
    (CANCELLED, 'CANCELLED'),
    (COMPLETED, 'COMPLETED'),
    (HOLD, 'HOLD')
)
SHOP_ORDER_STATUSES = (
        (PENDING,'PENDING'),
        (READY,'READY'),
        (NEED_YOUR_CALL,'NEED_YOUR_CALL'),
        (CANT_REPAIR,'CANT_REPAIR'),
    )

class BaseOrder(models.Model):
    ref           = models.CharField(max_length=255)
    imei          = models.CharField(max_length=15, validators=[validate_imei])
    brand         = models.ForeignKey(Brand, related_name="order_brand", blank=True, null=True, default=None)
    model         = models.ForeignKey(Model, related_name="order_model", blank=True, null=True, default=None)
    amount        = models.DecimalField(max_digits=9, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))], default=0)
    paid          = models.BooleanField(default=False, editable=True)
    created       = models.DateTimeField(auto_now_add=True)
    delivery_time = models.DateTimeField(auto_now_add=True,blank=True, null=True)
    deleted       = models.BooleanField(default=False, editable=True)


    def __str__(self):
        return self.ref
        
    # class Meta:
    #     abstract = True

class Charges(models.Model):
    charge = models.CharField(max_length=30,unique=True)
    value = models.CharField(max_length=4)

class ServerOrder(BaseOrder):
    shop = models.ForeignKey(Shop, related_name="shop_server_order")
    server = models.ForeignKey(Server, related_name="server_order")
    endpoint = models.ForeignKey(Endpoint)
    service = models.CharField(max_length=255)
    cancellation_time = models.DateTimeField(blank=True, null=True)
    urpsm_charge = models.DecimalField(max_digits=12, decimal_places=2, default='0', null=False, blank=False)
    urpsm_charge_factor = models.DecimalField(max_digits=12, decimal_places=2, default='0', null=False, blank=False)
    refund_amount = models.DecimalField(max_digits=12, decimal_places=2, default='0', null=False, blank=False)
    status = models.CharField(choices=ORDER_STATUSES, null=False, default=COMPLETED, max_length=255)

    @property
    def get_service(self):
        return unicode(self.service)

    class Meta:
        verbose_name        = "Server order"
        verbose_name_plural = "Server orders"


class ShopOrder(BaseOrder):
    shop = models.ForeignKey(Shop, related_name="client_server_order")
    client = models.ForeignKey(Client)
    status = models.CharField(choices=SHOP_ORDER_STATUSES, null=False, default=READY, max_length=255)

    class Meta:
        verbose_name        = "Shop order"
        verbose_name_plural = "Shop orders"


# class Order(models.Model):
# # uuid = UUIDField(auto=True)
# ref = models.CharField(max_length=255)
#     imei = models.CharField(max_length=15)
#     shop = models.ForeignKey(Shop)
#     endpoint = models.ForeignKey(Endpoint)
#     service = models.CharField(max_length=255)
#     amount  = models.CharField(max_length=50, default='0')
#     paid    = models.BooleanField(default=False, editable=True)

#     created = models.DateTimeField(auto_now_add=True)

#     class Meta:
#         verbose_name = "Order"
#         verbose_name_plural = "Orders"

#     def __str__(self):
#         return self.imei

#     @property
#     def get_service(self):
#         services = json.loads(self.endpoint.service)
#         return unicode(services.get(self.service))

app/order/forms.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import
from django.core.exceptions import ValidationError
from django import forms
from .models import ServerOrder
from app.endpoint.models import Endpoint, Network
from smart_selects.widgets import ChainedSelect
from app.antifraud.validators import validate_imei


class ServerOrderForm(forms.ModelForm):
    def __init__(self,*args, **kwargs):
        super(ServerOrderForm, self).__init__(*args, **kwargs)

    def clean_imei(self):
        validate_imei(self.cleaned_data.get('imei'))
        return self.cleaned_data.get('imei')

    class Meta:

        model = ServerOrder
        fields = ('endpoint', 'service', 'imei', 'brand', 'model')
        widgets = {
            'imei': forms.TextInput(attrs={'class': 'form-control',
                                           'placeholder': 'Imei'}),
            'brand': forms.Select(
                attrs={'class': 'form-control searchselect'}
            ),
            'model': ChainedSelect(
                app_name='phone',
                model_name='model',
                chain_field='brand',
                model_field='brand',
                show_all=False,
                auto_choose=False,
                attrs={'class': 'form-control searchselect'},
                # select2_options={"width": "100%"}
            ),
        }

templates/urpsm/endpoint/endpoint_confirm_delete.html
{% extends "urpsm/v2/base_manager_v2.html" %}
{% load i18n %}

{% block title %}{% trans "API Provider" %}{% endblock %}
{% block heading %} {% trans 'API' %} {% endblock %}
{% block subheading %} {% trans 'Provide an API Server' %}{% endblock %}
{% block breadcrumb %}
<li>
    <a href="{% url 'endpoints' %}" title="clients">{% trans 'endpoints'|capfirst %}</a>
</li>
<li class="active">{% trans 'add'|capfirst %}</li>
{% endblock %}

{% block content %}
<section class="content">
<div class="box">
    <div class="box-header">
        <h3 class="box-title">{% trans 'delete your provider API'|capfirst %}</h3>
    </div>
    <div class="box-body" >	
	<form action="" method="post">{% csrf_token %}
	    <p>{% trans 'are you sure you want to delete?'|capfirst %} "{{ object }}"?</p>
	    <input type="submit" class="btn btn-danger" value="{% trans 'confirm'|capfirst %}" />
	</form>
</div>
</div>
</section>
{% endblock %}

templates/urpsm/endpoint/networks.html
{% extends "urpsm/v2/base_manager_v2.html" %}
{% load i18n %} 
{% load networks_tag %} 
{% load static from staticfiles %}
{% block title %}{% trans "API Networks" %}{% endblock %}
{% block heading %} {% trans 'API'|capfirst %} {% endblock %}
{% block subheading %} {% trans 'Provide an API Networks'|capfirst %}{% endblock %}
{% block breadcrumb %}
<li>
    <a href="{% url 'endpoints' %}" title="clients">{% trans 'endpoints'|capfirst %}</a>
</li>
<li class="active">{% trans 'add'|capfirst %}</li>
{% endblock %}

{% block content %}
<section class="content">
<div class="box">
    <div class="box-header">
        <h3 class="box-title">{% trans 'choose your provider API networks and services'|capfirst %}</h3>
    </div>
    <div class="box-body" >	
		<form id="netform" action="" method="post">{% csrf_token %}
		<div class="row">
			    <div class="col-sm-5">
			        <!-- <select name="from" id="id_networks" class="form-control" size="8" multiple="multiple">
			            <id_networks label="Swedish Cars">
			                <option value="volvo">Volvo</option>
			                <option value="saab">Saab</option>
			            </id_networks>
			            <id_networks label="German Cars">
			                <option value="mercedes">Mercedes</option>
			                <option value="audi">Audi</option>
			            </id_networks>
			            <option value="1">C++</option>
			        </select> -->
			        {{form.networks}}
			    </div>
			    
			    <div class="col-sm-2">
			    	<button type="button" id="id_networks_undo" class="btn btn-info btn-block">{% trans 'undo'|capfirst %}</button>
			        <button type="button" id="id_networks_rightAll" class="btn btn-block"><i class="glyphicon glyphicon-forward"></i></button>
			        <button type="button" id="id_networks_rightSelected" class="btn btn-block"><i class="glyphicon glyphicon-chevron-right"></i></button>
			        <button type="button" id="id_networks_leftSelected" class="btn btn-block"><i class="glyphicon glyphicon-chevron-left"></i></button>
			        <button type="button" id="id_networks_leftAll" class="btn btn-block"><i class="glyphicon glyphicon-backward"></i></button>
			        <button type="button" id="id_networks_redo" class="btn btn-warning btn-block">{% trans 'redo'|capfirst %}</button>
			    </div>
			    
		        {{form.raw}}
			    <div class="col-sm-5">
			        <!-- <select name="to" id="id_networks_to" class="form-control" size="11" multiple="multiple">
			            
			        </select> -->
			        {{form.networks_to}}
			    </div>
			</div>
			<div class="pull-right">
				<input id="submit" class="btn btn-primary" type="submit" value="{% trans 'save'|capfirst %}" onclick="return false">
			</div>
		</form>
		
		
    </div>
</div>
<div class="box">
    <div class="box-header">
        <h3 class="box-title">{% trans 'list of your working services'|capfirst %}</h3>
    </div>
    <div class="box-body networks table-responsive">
        <table class="table table-hover table-condensed">
            <thead>
                <tr>
                    <th>{% trans 'network'|capfirst %}</th>
                    <th>{% trans 'service'|capfirst %}</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div>
</div>
</section>
<script type="text/javascript">
jQuery(document).ready(function($) {
    $("#id_networks").multiselect();

    $networks = [{% get_netowrks_and_services %}];
    $user_networks = [{% get_user_netowrks_and_services %}];
    for (var network in $user_networks[0]){
        console.log(network, $user_networks[0][network]);
        $service = '<tr><td>'+network+'</td><td>'+$user_networks[0][network]+'</td></tr>';
        $(".networks tbody").append($service);
    }

    function get_network(id, name){
    	console.log(id, name);
    	
    	for (var network_name in $networks[0]){
    		var services = $networks[0][network_name];
    		for (var service_item in services){
    			service_obj = $networks[0][network_name][service_item]
    			for(var service_id in service_obj){
    				service_name = service_obj[service_id]
	    			console.log(service_id, service_name);
	    			if (name == service_name && id==service_id){
	    				console.log('Bingo!!')
	    			    return network_name;
	   				}
       			}
    		}
    	}
    }
    	
    
    $("#submit").click(function(e){
    	e.preventDefault();
    	$("#id_networks_to option").prop("selected", "selected");
    	var foo = {}; 
    	$('#id_networks_to :selected').each(function(i, selected){ 
    		network = get_network($(selected).val() ,$(selected).text());
    		// console.log(network);
  			foo[i] = { 'endpoint': '{{form.instance.pk}}', 'network': network, 'id' : $(selected).val() , 'service': $(selected).text() }; 
		});
    	try{
    		console.log(foo);
    		console.log(JSON.stringify(foo));
    		console.log($.param(foo));
    	}catch(e){}
    	
    	var url = "{% url 'endpoint-services' %}";
    	$.ajax({
    		url: url,
    		data: {data:JSON.stringify(foo)},
    		// contentType: 'application/json',
    		dataType:'json',
    		type:'post',
    		success: function(response){
    			if (response.status){
    				alert('{% trans "your networks have been successfully saved !!"|capfirst %}');
    			}else{
    				alert('{% trans "Your networks have not been saved. Please try again."|capfirst %}');

    			}
    		},
    	});

    	
    });
});
</script>
{% endblock %}
{% block extrajs%}
<script type="text/javascript" src="{% static 'v2/js/multiselect.min.js' %}"></script>
{% endblock extrajs%}

templates/urpsm/endpoint/unlocking.html
{% extends "urpsm/v2/base_manager_v2.html" %}
{% load i18n thumbnail staticfiles account_tags %}
{% block title %} {% trans 'unlocking'|capfirst %} {% endblock %}
{% block extrahead %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.2.0/jquery-confirm.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.2.0/jquery-confirm.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
  $(".searchselect").select2();
});

</script>

{% endblock %}
{% block heading %} {% trans 'unlocking'|capfirst %} {% endblock %}
{% block breadcrumb %}
<li class="active">{% trans 'unlocking'|capfirst %}</li>
{% endblock %}
{% block content %}
<section class="content">
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">{% trans 'unlocking order'|capfirst %}</h3>
        </div>
        <div class="box-body">
            {% if success_msg %}
            <div class="alert alert-success">{{ success_msg }}</div>
            {% endif %}
            {% if error_msg %}
            <div class="alert alert-danger">{{ error_msg }}</div>
            {% endif %}
            <div class="form-group">
                <label for="Network">Network</label>

                <select class="form-control searchselect" id="id_network" name="network">
                    <option value="" selected="selected">SELECT A NETWORK</option>
                    {% for obj in returnObj %}
                    <optgroup label="{{ obj.0 }}">
                        {% for network in obj.1 %}
                        <option value="{{ network.1 }}" endpoint="{{network.0}}">{{ network.2 }}</option>
                        {% endfor %}
                    </optgroup>
                    {% endfor %}
                </select>

            </div>
        </div>

        <form action="" method="post" accept-charset="utf-8" id="unlockForm">
            {% csrf_token %}
            <div class="box-body">
                <input type="hidden" id="id_endpoint" name="endpoint" value="{{ endpointid }}">


                <div class="form-group">
                    <label for="{{form.service.label}}">{{ form.service.label }}</label>

                    {{ form.service }}
                    {% if form.service.errors %}
                    {{ form.service.errors }}
                    {% endif %}
                </div>

                <div class="form-group">
                    <label for="{{form.imei.label}}">{{ form.imei.label }}</label>

                    {{ form.imei }}
                    {% if form.imei.errors %}
                    {{ form.imei.errors }}
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="{{form.brand.label}}">{{ form.brand.label }}</label>

                    {{ form.brand }}
                    {% if form.brand.errors %}
                    {{ form.brand.errors }}
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="{{form.model.label}}">{{ form.model.label }}</label>

                    {{ form.model }}
                    {% if form.model.errors %}
                    {{ form.model.errors }}
                    {% endif %}
                </div>
                <!-- <div class="error-page">
                            <h2 class="headline text-yellow"> <i class="fa fa-unlock"></i></h2>
                            <div class="error-content">
                              <h3><i class="fa fa-warning text-yellow"></i> Unlocking server.</h3>
                              <p>
                                We are working hard to bring this feature on the next version of URPSM, so stay tunned.
                              </p>

                              <p>
                                  For more information you can reach us at <a href="mailto:contact@urpsm.com?subject=feedback">contact@urpsm.com</a>
                              </p>
                            </div>
                          </div> -->
                <div id="service_detail"></div>
            </div>
            <div class="box-footer">
                <input class="btn btn-primary" type="button" id="formSubmitBtn" value="{% trans 'Save' %}"/>
            </div>
        </form>
    </div>
</section>
{% endblock %}

{% block extrajs %}
<script src="{{ STATIC_URL }}js/blockui.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" charset="utf-8">

// unlocking


(function($){

  $(document).ajaxStart($.blockUI).ajaxStop($.unblockUI);



  $('#id_service, #id_imei, #id_brand, #id_model').parent().hide();

        $.ajax({
       url: '/get_services/',
       type: 'POST',
       dataType: 'json',
       success: function(data){
        console.log(data);
       }
     });

  if ( $('#network').val() != "undefined" && $('#id_network').val() != "") {
      var $network = $('#id_network').val();
        $.ajax({
       url: '/get_services/',
       type: 'POST',
       dataType: 'json',
       data: {network: $network},
       success: function(data){
        var services = $.parseJSON(data.services);
        var options = '';
        for(var service in services)
        {
        if(service==="network")continue;
          options += '<option value="'+ service + '">' + services[service] +'</option>';
        }
        $('#id_service').parent().show();
        $(".searchselect").select2('destroy');
        $('#id_service').replaceWith('<select class="form-control searchselect" id="id_service" name="service">'+ options +'</select>');
        $('#id_imei').parent().show();
        $('#id_brand').parent().show();
        $('#id_model').parent().show();
       }
     });
  }
  
  $('#id_network').on('change', function(event){
    var $network = $('#id_network').val();
    var $endpoint = $('#id_network option:selected').attr('endpoint');
$('#id_endpoint').val($endpoint);

    $.ajax({
       url: '/get_services/',
       type: 'POST',
       dataType: 'json',
       data: {network: $network,endpoint: $endpoint},
       success: function(data){
        var services = $.parseJSON(data.services);
        var options = '';
        for(var service in services)
        {
          if(service==="network")continue;
          options += '<option value="'+ service + '">' + services[service] +'</option>';
        }
        $('#id_service').parent().show();
        $(".searchselect").select2('destroy');
        $('#id_service').replaceWith('<select class="form-control searchselect" id="id_service" name="service">'+ options +'</select>');
        $('#id_imei').parent().show();
        $('#id_brand').parent().show();
        $('#id_model').parent().show();
         $(".searchselect").select2();

        get_service_detail($('#id_endpoint').val(), $('#id_service').val());


       }
     })
      
  });


  if ($('#id_service').val() != 'undefined' && $('#id_service').val() != "") {
      var $endpoint = $('#id_endpoint').val();
      get_service_detail($endpoint, $('#id_service').val());
  }


  $('form').delegate("#id_service",'change', function(event){
      var $endpoint = $('#id_endpoint').val();
      get_service_detail($endpoint, $(this).val());
  });

  function get_service_detail(endpoint_id, service_id)
  {
    $.ajax({
      url: '/get_service_detail/',
      type: 'POST',
      dataType: 'json',
      data: {service: service_id, endpoint: endpoint_id},
      success: function(data){
        if (data) {
          var html = '<p><h3> Credit : $'+ data['credit'] + ' USD</h3> </p>';
              if(data['time']){
                html += '<p><h3> Time : '+ data['time'] + '</h3></p>';


                $('#formSubmitBtn').click(function(event){
        $.confirm({
            title: 'Are you sure ?',
            content: 'You are placing an order which is going to cost '+data['credit']+' and take '+data['time'],
            buttons: {
                confirm: function () {
                      $('#unlockForm').submit();
                    },
                cancel: function () {
                      $.alert('Canceled!');
                        }
                }
            });

        });
              }

          $('#service_detail').addClass('alert alert-info').html(html);
        }
      },
    });

    
  }

})(jQuery)    

</script>
{% endblock %}