app/component/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import patterns, url
from .views import (CreateComponentView, ComponentView, UpdateComponentView, DeleteComponentView,
   ComponentDetailView, ComponentListView, ComponentSearchView, )

urlpatterns = patterns('',
                       url(r'^$', ComponentView.as_view(),
                           name='components'),
                       url(r'^add/$', CreateComponentView.as_view(),
                           name='component-create'),
                       url(r'^(?P<pk>\d+)/edit/$',
                           UpdateComponentView.as_view(), name='component-edit'),
                       url(r'^(?P<pk>\d+)/delete/$',
                           DeleteComponentView.as_view(), name='component-delete'),
                       url(r'^search/?$', ComponentSearchView.as_view(), name='components-search'),
                       url(r'^shops-components/?$', ComponentListView.as_view(), name='components-list'),
                       url(r'^(?P<pk>[\d-]+)/(?P<slug>[\w-]+)/detail$', ComponentDetailView.as_view(), name='component-detail'),
                       )

mobilify/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.http import HttpResponse

from app.dash.sites import SitePlus
from django.conf.urls.i18n import i18n_patterns
from app.account.views import Error404View

admin.site = SitePlus()
admin.autodiscover()

urlpatterns = i18n_patterns('',
                       # Examples:
                       # url(r'^$', 'mobilify.views.home', name='home'),
                       url(r'', include('app.public.urls')),
                       url(r'^orders/', include('app.order.urls')),
                       url(r'^accounts/', include('app.account.urls')),
                       url(r'^shop/', include('app.shop.urls')),
                       url(r'^clients/', include('app.client.urls')),
                       url(r'^components/', include('app.component.urls')),
                       url(r'^server/', include('app.server.urls')),
                       url(r'^select2/', include('django_select2.urls')),
                       url(r'^chaining/', include('smart_selects.urls')),
                       url(r'^notifications/', include('app.notifications.urls')),
                       url(r'^payments/', include('app.payment.urls')),
                       url(r'^tickets/', include('app.ticket.urls')),
                       url(r'^reviews/', include('app.ureview.urls')),
                       url(r'^manager/', include('app.dash.urls')),
                       url(r'^endpoint/', include('app.endpoint.dash_urls')),
                       url(r'^location_field/',
                           include('location_field.urls')),
                       url(r'^payment/',
                           include('paypal.standard.ipn.urls')),
                       url(r'^error', Error404View.as_view(), name='error-404'),
                       url(r'secure/', include('two_factor.urls', 'two_factor')),
                       url(r'sitemap.xml',lambda r: HttpResponse(open('sitemap.xml','r').read(),status=200)))

urlpatterns +=    patterns('',url(r'^urpsmadminp/', include(admin.site.urls)),
                       url(r'^', include('app.endpoint.urls')),
                       url(r'^', include('app.launch.urls')),
                       url(r'', include('social.apps.django_app.urls', namespace='social')),
                       url(r'^search/', include('app.search.urls')),
                       url(r'session_security/', include('session_security.urls')),
                    )

if settings.DEBUG:
    urlpatterns +=patterns('',
                            (r'^static/(?P<path>.*)$', 'django.views.static.serve',
                             {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
                            )

    urlpatterns += patterns('',
                            (r'^media/(?P<path>.*)$', 'django.views.static.serve',
                             {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
                            )

app/component/models.py
# -*- coding: utf-8 -*-
from decimal import Decimal
from django.db import models
from django.core.validators import MinValueValidator
from slugify import slugify

from smart_selects.db_fields import ChainedForeignKey
# from easy_thumbnails.fields import ThumbnailerImageField
from versatileimagefield.fields import VersatileImageField
from versatileimagefield.placeholder import OnStoragePlaceholderImage
from mobilify.custom_storages import StaticStorage

from app.shop.models import Shop
from app.phone.models import Brand, Model
from app.search.index import Indexed, SearchField, FilterField, RelatedFields


class Type(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(editable=False, db_index=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return unicode(self.name)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Type, self).save(*args, **kwargs)


class Component(models.Model, Indexed):

    CURRENCY = (("AED", "United Arab Emirates Dirham"),
                ("AFN", "Afghan Afghani"),
                ("ALL", "Albanian Lek"),
                ("AMD", "Armenian Dram"),
                ("ANG", "Netherlands Antillean Guilder"),
                ("AOA", "Angolan Kwanza"),
                ("ARS", "Argentine Peso"),
                ("AUD", "Australian Dollar"),
                ("AWG", "Aruban Florin"),
                ("AZN", "Azerbaijani Manat"),
                ("BAM", "Bosnia-Herzegovina Convertible Mark"),
                ("BBD", "Barbadian Dollar"),
                ("BDT", "Bangladeshi Taka"),
                ("BGN", "Bulgarian Lev"),
                ("BHD", "Bahraini Dinar"),
                ("BIF", "Burundian Franc"),
                ("BMD", "Bermudan Dollar"),
                ("BND", "Brunei Dollar"),
                ("BOB", "Bolivian Boliviano"),
                ("BRL", "Brazilian Real"),
                ("BSD", "Bahamian Dollar"),
                ("BTC", "Bitcoin"),
                ("BTN", "Bhutanese Ngultrum"),
                ("BWP", "Botswanan Pula"),
                ("BYR", "Belarusian Ruble"),
                ("BZD", "Belize Dollar"),
                ("CAD", "Canadian Dollar"),
                ("CDF", "Congolese Franc"),
                ("CHF", "Swiss Franc"),
                ("CLF", "Chilean Unit of Account (UF)"),
                ("CLP", "Chilean Peso"),
                ("CNY", "Chinese Yuan"),
                ("COP", "Colombian Peso"),
                ("CRC", "Costa Rican Colón"),
                ("CUC", "Cuban Convertible Peso"),
                ("CUP", "Cuban Peso"),
                ("CVE", "Cape Verdean Escudo"),
                ("CZK", "Czech Republic Koruna"),
                ("DJF", "Djiboutian Franc"),
                ("DKK", "Danish Krone"),
                ("DOP", "Dominican Peso"),
                ("DZD", "Algerian Dinar"),
                ("EEK", "Estonian Kroon"),
                ("EGP", "Egyptian Pound"),
                ("ERN", "Eritrean Nakfa"),
                ("ETB", "Ethiopian Birr"),
                ("EUR", "Euro"),
                ("FJD", "Fijian Dollar"),
                ("FKP", "Falkland Islands Pound"),
                ("GBP", "British Pound Sterling"),
                ("GEL", "Georgian Lari"),
                ("GGP", "Guernsey Pound"),
                ("GHS", "Ghanaian Cedi"),
                ("GIP", "Gibraltar Pound"),
                ("GMD", "Gambian Dalasi"),
                ("GNF", "Guinean Franc"),
                ("GTQ", "Guatemalan Quetzal"),
                ("GYD", "Guyanaese Dollar"),
                ("HKD", "Hong Kong Dollar"),
                ("HNL", "Honduran Lempira"),
                ("HRK", "Croatian Kuna"),
                ("HTG", "Haitian Gourde"),
                ("HUF", "Hungarian Forint"),
                ("IDR", "Indonesian Rupiah"),
                ("ILS", "Israeli New Sheqel"),
                ("IMP", "Manx pound"),
                ("INR", "Indian Rupee"),
                ("IQD", "Iraqi Dinar"),
                ("IRR", "Iranian Rial"),
                ("ISK", "Icelandic Króna"),
                ("JEP", "Jersey Pound"),
                ("JMD", "Jamaican Dollar"),
                ("JOD", "Jordanian Dinar"),
                ("JPY", "Japanese Yen"),
                ("KES", "Kenyan Shilling"),
                ("KGS", "Kyrgystani Som"),
                ("KHR", "Cambodian Riel"),
                ("KMF", "Comorian Franc"),
                ("KPW", "North Korean Won"),
                ("KRW", "South Korean Won"),
                ("KWD", "Kuwaiti Dinar"),
                ("KYD", "Cayman Islands Dollar"),
                ("KZT", "Kazakhstani Tenge"),
                ("LAK", "Laotian Kip"),
                ("LBP", "Lebanese Pound"),
                ("LKR", "Sri Lankan Rupee"),
                ("LRD", "Liberian Dollar"),
                ("LSL", "Lesotho Loti"),
                ("LTL", "Lithuanian Litas"),
                ("LVL", "Latvian Lats"),
                ("LYD", "Libyan Dinar"),
                ("MAD", "Moroccan Dirham"),
                ("MDL", "Moldovan Leu"),
                ("MGA", "Malagasy Ariary"),
                ("MKD", "Macedonian Denar"),
                ("MMK", "Myanma Kyat"),
                ("MNT", "Mongolian Tugrik"),
                ("MOP", "Macanese Pataca"),
                ("MRO", "Mauritanian Ouguiya"),
                ("MTL", "Maltese Lira"),
                ("MUR", "Mauritian Rupee"),
                ("MVR", "Maldivian Rufiyaa"),
                ("MWK", "Malawian Kwacha"),
                ("MXN", "Mexican Peso"),
                ("MYR", "Malaysian Ringgit"),
                ("MZN", "Mozambican Metical"),
                ("NAD", "Namibian Dollar"),
                ("NGN", "Nigerian Naira"),
                ("NIO", "Nicaraguan Córdoba"),
                ("NOK", "Norwegian Krone"),
                ("NPR", "Nepalese Rupee"),
                ("NZD", "New Zealand Dollar"),
                ("OMR", "Omani Rial"),
                ("PAB", "Panamanian Balboa"),
                ("PEN", "Peruvian Nuevo Sol"),
                ("PGK", "Papua New Guinean Kina"),
                ("PHP", "Philippine Peso"),
                ("PKR", "Pakistani Rupee"),
                ("PLN", "Polish Zloty"),
                ("PYG", "Paraguayan Guarani"),
                ("QAR", "Qatari Rial"),
                ("RON", "Romanian Leu"),
                ("RSD", "Serbian Dinar"),
                ("RUB", "Russian Ruble"),
                ("RWF", "Rwandan Franc"),
                ("SAR", "Saudi Riyal"),
                ("SBD", "Solomon Islands Dollar"),
                ("SCR", "Seychellois Rupee"),
                ("SDG", "Sudanese Pound"),
                ("SEK", "Swedish Krona"),
                ("SGD", "Singapore Dollar"),
                ("SHP", "Saint Helena Pound"),
                ("SLL", "Sierra Leonean Leone"),
                ("SOS", "Somali Shilling"),
                ("SRD", "Surinamese Dollar"),
                ("STD", u"São Tomé and Príncipe Dobra"),
                ("SVC", u"Salvadoran Colón"),
                ("SYP", "Syrian Pound"),
                ("SZL", "Swazi Lilangeni"),
                ("THB", "Thai Baht"),
                ("TJS", "Tajikistani Somoni"),
                ("TMT", "Turkmenistani Manat"),
                ("TND", "Tunisian Dinar"),
                ("TOP", "Tongan Paʻanga"),
                ("TRY", "Turkish Lira"),
                ("TTD", "Trinidad and Tobago Dollar"),
                ("TWD", "New Taiwan Dollar"),
                ("TZS", "Tanzanian Shilling"),
                ("UAH", "Ukrainian Hryvnia"),
                ("UGX", "Ugandan Shilling"),
                ("USD", "United States Dollar"),
                ("UYU", "Uruguayan Peso"),
                ("UZS", "Uzbekistan Som"),
                ("VEF", "Venezuelan Bolívar Fuerte"),
                ("VND", "Vietnamese Dong"),
                ("VUV", "Vanuatu Vatu"),
                ("WST", "Samoan Tala"),
                ("XAF", "CFA Franc BEAC"),
                ("XAG", "Silver (troy ounce)"),
                ("XAU", "Gold (troy ounce)"),
                ("XCD", "East Caribbean Dollar"),
                ("XDR", "Special Drawing Rights"),
                ("XOF", "CFA Franc BCEAO"),
                ("XPD", "Palladium Ounce"),
                ("XPF", "CFP Franc"),
                ("XPT", "Platinum Ounce"),
                ("YER", "Yemeni Rial"),
                ("ZAR", "South African Rand"),
                ("ZMK", "Zambian Kwacha (pre-2013)"),
                ("ZMW", "Zambian Kwacha"),
                ("ZWL", "Zimbabwean Dollar"),
                )

    image = VersatileImageField(upload_to='components/%Y/%m/', blank=True,
        placeholder_image=OnStoragePlaceholderImage(
            path='v2/images/75-752.png',
            storage=StaticStorage()
            )
        
        )
    title = models.CharField(max_length=255)
    slug = models.SlugField(editable=False, db_index=True)
    brand = models.ForeignKey(Brand)
    model = ChainedForeignKey(Model,
                              chained_field='brand',
                              chained_model_field='brand',
                              show_all=False, auto_choose=True)
    type = models.ForeignKey(Type, related_name='component_type')

    description = models.TextField()
    currency = models.CharField(max_length=64, choices=CURRENCY, default='USD')
    price = models.DecimalField(
        max_digits=9, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))], default=0)
    shop = models.ForeignKey(Shop, related_name='component_shop')
    sold = models.BooleanField(default=False)
    deleted = models.BooleanField(default=False)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    search_fields = [
        SearchField('title', partial_match=True, boost=10),

app/component/forms.py
from __future__ import absolute_import
from django import forms

from smart_selects.widgets import ChainedSelect
from django_select2.widgets import Select2Widget
from .models import Component

class SfWidget(Select2Widget, ChainedSelect):
    pass


class CreateComponentForm(forms.ModelForm):

    class Meta:
        model = Component
        exclude = ('sold', 'deleted', 'shop', )
        widgets = {
            'image': forms.FileInput(attrs={'class': 'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title'}),
            'brand': forms.Select(
                # attrs={'class': 'form-control'}
                ),
            # 'brand': Select2Widget(select2_options={'width': '100%'}),
            'model': ChainedSelect(
                app_name='phone',
                model_name='model',
                chain_field='brand',
                model_field='brand',
                show_all=False,
                auto_choose=False, 
                # attrs={'class': 'form-control'},
                # select2_options={'width': '100%'}
            ),
            'type': forms.Select(
                # attrs={'class': 'form-control'}
                ),
            # 'type': Select2Widget(select2_options={'width': '100%'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'min': '0'}),
            'currency': forms.Select(attrs={'class': 'form-control',}),

        }


class UpdateComponentForm(forms.ModelForm):

    class Meta:
        model = Component
        exclude = ('deleted', 'shop')
        widgets = {
            'image': forms.FileInput(attrs={'class': 'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title'}),
            'brand': Select2Widget(select2_options={'width': '100%'}),
            'model': SfWidget(
                app_name='phone',
                model_name='model',
                chain_field='brand',
                model_field='brand',
                show_all=False,
                auto_choose=False, 
                # attrs={'class': 'form-control'},
                select2_options={'width': '100%'}

            ),
            'type': Select2Widget(select2_options={'width': '100%'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'min': '0'}),
            'currency': forms.Select(attrs={'class': 'form-control',}),
            

        }

templates/urpsm/components/create.html
{% extends "urpsm/v2/base_manager_v2.html" %}
{% load i18n staticfiles%}
{% block title %} Add new component {% endblock %}
{% block heading %} Component {% endblock %}
{% block subheading %} {% trans 'adding new component'|capfirst %}{% endblock %}
{% block breadcrumb %}
<li><a href="{% url 'components' %}" title="components">{% trans 'components'|capfirst %}</a></li>
<li class="active">{% trans 'add'|capfirst %}</li>
{% endblock %}
{% block content %}
<section class="content">
<div class="box">
    <div class="box-header">
        <h3 class="box-title">{% trans 'new component'|capfirst %}</h3>
    </div>

    <form action="" method="post" accept-charset="utf-8" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="box-body">
            <div class="col-md-12">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="{{ form.title.label }}"> {{ form.title.label }}</label>
                            {{ form.title }}
                                    {% if form.title.errors %}
                                        {{ form.title.errors }}
                                    {% endif %}
                        
                     </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="{{ form.image.label }}"> {{ form.image.label }}</label>
                        {{ form.image }}
                                {% if form.image.errors %}
                                    {{ form.image.errors }}
                                {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="{{ form.brand.label }}"> {{ form.brand.label }}</label>
                        {{ form.brand }}
                                {% if form.brand.errors %}
                                    {{ form.brand.errors }}
                                {% endif %}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                    <label for="{{ form.model.label }}"> {{ form.model.label }}</label>
                        {{ form.model }}
                                {% if form.model.errors %}
                                    {{ form.model.errors }}
                                {% endif %}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="{{ form.type.label }}"> {{ form.type.label }}</label>
                        {{ form.type }}
                                {% if form.type.errors %}
                                    {{ form.type.errors }}
                                {% endif %}
                    </div>
                </div>
            </div>
            <div class="form-group">
            <label for="{{ form.description.label }}"> {{ form.description.label }}</label>
                {{ form.description }}
                        {% if form.description.errors %}
                            {{ form.description.errors }}
                        {% endif %}
            </div>
            <div class="form-group">
                <label for="{{ form.price.label }}"> {{ form.price.label }}</label>
                <div class="row">
                    <div class="col-md-1">
                        {{ form.currency }}
                    </div>
                    <div class="col-md-9">
                        <div class="input-group">
                        {{ form.price }}</div>
                        {% if form.price.errors %}
                            {{ form.price.errors }}
                        {% endif %}
                    </div>
                </div>
            </div>
    </div>

    <div class="box-footer">
<input class="btn btn-primary" type="submit" value="{% trans 'Save' %}" />
    </div>
    </form>
</div>
</section>
{% endblock %}

{% block extrajs %}
<script src="{% static "suit-redactor/redactor/redactor.min.js" %}" type="text/javascript"></script>
<script src="{% static "django_select2/js/select2.min.js" %}" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(document).ready(function($) {
        $('#id_model, #id_brand, #id_type').select2({'width': '100%'});
        $('#id_description').redactor({
                lang: 'en',
                buttons: ['html', '|', 'formatting', '|', 'bold', 'italic', '|',
                            'unorderedlist', 'orderedlist', 'outdent', 'indent',
                            'alignment', 'horizontalrule', 'underline'],
        });
    });
</script>
{% endblock %}
{% block extrastyle %}
<link rel="stylesheet" href="{% static "suit-redactor/redactor/redactor.css" %}">
<link href="{% static "django_select2/css/select2.min.css" %}" rel="stylesheet" type="text/css" />
{% endblock %}

templates/urpsm/components/update.html
{% extends "urpsm/v2/base_manager_v2.html" %}
{% load i18n staticfiles thumbnail %}
{% block title %} {% trans 'edit component'|capfirst %} {% endblock %}
{% block heading %} {% trans 'component'|capfirst %} {% endblock %}
{% block subheading %} {% trans 'editing component'|capfirst %}{% endblock %}
{% block breadcrumb %}
<li><a href="{% url 'components' %}" title="components">{% trans 'components'|capfirst %}</a></li>
<li class="active">{% trans 'edit'|capfirst %}</li>
{% endblock %}
{% block content %}
<section class="content">
<div class="box">
    <div class="box-header">
        <h3 class="box-title">{% trans 'edit component'|capfirst %}</h3>
    </div>

    <div class="row">
        <div class="col-md-8 col-md-offset-3 col-xs-offset-1">
            <img class="img img-responsive" src="{{ object.image.thumbnail.300x300 }}" alt="{{ object.title }}">
        </div>
    </div>

    <form action="" method="post" accept-charset="utf-8" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="box-body">
            <div class="form-group">
            <label for="{{ form.image.label }}"> {{ form.image.label }}</label>
                {{ form.image }}
                        {% if form.image.errors %}
                            {{ form.image.errors }}
                        {% endif %}
            </div>
            <div class="form-group">
                <label for="{{ form.title.label }}"> {{ form.title.label }}</label>
                {{ form.title }}
                        {% if form.title.errors %}
                            {{ form.title.errors }}
                        {% endif %}
            </div>
            <div class="form-group">
                <label for="{{ form.brand.label }}"> {{ form.brand.label }}</label>
                {{ form.brand }}
                        {% if form.brand.errors %}
                            {{ form.brand.errors }}
                        {% endif %}
            </div>
            <div class="form-group">
                <label for="{{ form.model.label }}"> {{ form.model.label }}</label>
                {{ form.model }}
                        {% if form.model.errors %}
                            {{ form.model.errors }}
                        {% endif %}
            </div>
            <div class="form-group">
                <label for="{{ form.type.label }}"> {{ form.type.label }}</label>
                {{ form.type }}
                        {% if form.type.errors %}
                            {{ form.type.errors }}
                        {% endif %}
            </div>
            <div class="form-group">
            <label for="{{ form.description.label }}"> {{ form.description.label }}</label>
                {{ form.description }}
                        {% if form.description.errors %}
                            {{ form.description.errors }}
                        {% endif %}
            </div>
            <div class="form-group">
                <label for="{{ form.price.label }}"> {{ form.price.label }}</label>
                <div class="row">
                    <div class="col-md-1">
                        {{ form.currency }}
                    </div>
                    <div class="col-md-9">
                        <div class="input-group">
                        {{ form.price }}</div>
                        {% if form.price.errors %}
                            {{ form.price.errors }}
                        {% endif %}
                    </div>
                </div>
            </div>

<div class="row">
    <div class="col-xs-8">
    <div class="form-group">
      <div class="checkbox icheck">
        <label>
          {{ form.sold }} &nbsp; {% trans 'sold'|capfirst %}
        </label>
      </div>
    </div>
            </div>
</div>

    </div>

    <div class="box-footer">
<input class="btn btn-primary" type="submit" value="{% trans 'Save' %}" />
    </div>
    </form>
</div>
</section>
{% endblock %}

{% block extrajs %}
<script src="{% static "suit-redactor/redactor/redactor.min.js" %}" type="text/javascript"></script>
<script src="{% static "js/plugins/iCheck/icheck.min.js" %}" type="text/javascript"></script>
<script src="{% static "django_select2/js/select2.min.js" %}" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(document).ready(function($) {
        $('#id_model, #id_brand, #id_type').select2({'width': '100%'});
        $('#id_description').redactor({
                lang: 'en',
                buttons: ['html', '|', 'formatting', '|', 'bold', 'italic', '|',
                            'unorderedlist', 'orderedlist', 'outdent', 'indent',
                            'alignment', 'horizontalrule', 'underline'],
        });

        $(function () {
            $('input').iCheck({
              checkboxClass: 'icheckbox_square-blue',
              radioClass: 'iradio_square-blue',
              increaseArea: '20%' // optional
            });
        });

    });
</script>
{% endblock %}
{% block extrastyle %}
<link rel="stylesheet" href="{% static "suit-redactor/redactor/redactor.css" %}">
<link href="{% static "js/plugins/iCheck/square/blue.css" %}" rel="stylesheet" type="text/css" />
<link href="{% static "django_select2/css/select2.min.css" %}" rel="stylesheet" type="text/css" />
{% endblock %}